# Generated by Django 2.2.2 on 2019-12-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(max_length=2)),
                ('telephone', models.CharField(max_length=255)),
                ('date_rdv', models.DateField(blank=True, null=True)),
                ('heure_rdv', models.TimeField(blank=True, null=True)),
                ('date_contact', models.DateField(blank=True, null=True)),
                ('heure_contact', models.TimeField(blank=True, null=True)),
                ('motif', models.TextField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
