# Generated by Django 2.2 on 2019-06-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('naissance', models.DateField()),
                ('telephone', models.CharField(max_length=255)),
                ('rdv', models.DateTimeField(null=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
