# Generated by Django 2.2 on 2019-06-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
