# Generated by Django 2.2.2 on 2019-08-11 12:33

import clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190630_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='date_contact',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='rdv',
            field=models.DateTimeField(null=True, validators=[clients.validators.validate_rdv]),
        ),
    ]
