# Generated by Django 2.2.2 on 2019-08-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190811_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='rdv',
        ),
        migrations.AddField(
            model_name='clients',
            name='date_rdv',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='heure_contact',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='heure_rdv',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_contact',
            field=models.DateField(null=True),
        ),
    ]
