# Generated by Django 2.2.2 on 2019-08-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20190816_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
