# Generated by Django 2.2.2 on 2019-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20190816_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='sexe',
            field=models.CharField(default='H', max_length=2),
            preserve_default=False,
        ),
    ]
