# Generated by Django 2.2.2 on 2019-08-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clients_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='motif',
            field=models.TextField(null=True),
        ),
    ]
